You and I would have understood that sentence in a fraction of a second. But machines simply cannot process text data in raw form. They need us to break down the text into a numerical format that’s easily readable by the machine (the idea behind Natural Language Processing!).
## Convert text sentences into numeric vectors.

![Process](https://cdn-media-1.freecodecamp.org/images/qRGh8boBcLLQfBvDnWTXKxZIEAk5LNfNABHF)

- [Wikipidea Bow](https://en.wikipedia.org/wiki/Bag-of-words_model)
- [A Gentle Introduction to the Bag-of-Words Model](https://machinelearningmastery.com/gentle-introduction-bag-words-model/)


In [8]:
import nltk

In [9]:
paragraph =  """I have three visions for India. In 3000 years of our history, people from all over 
               the world have come and invaded us, captured our lands, conquered our minds. 
               From Alexander onwards, the Greeks, the Turks, the Moguls, the Portuguese, the British,
               the French, the Dutch, all of them came and looted us, took over what was ours. 
               Yet we have not done this to any other nation. We have not conquered anyone. 
               We have not grabbed their land, their culture, 
               their history and tried to enforce our way of life on them. 
               Why? Because we respect the freedom of others.That is why my 
               first vision is that of freedom. I believe that India got its first vision of 
               this in 1857, when we started the War of Independence. It is this freedom that
               we must protect and nurture and build on. If we are not free, no one will respect us.
               My second vision for India’s development. For fifty years we have been a developing nation.
               It is time we see ourselves as a developed nation. We are among the top 5 nations of the world
               in terms of GDP. We have a 10 percent growth rate in most areas. Our poverty levels are falling.
               Our achievements are being globally recognised today. Yet we lack the self-confidence to
               see ourselves as a developed nation, self-reliant and self-assured. Isn’t this incorrect?
               I have a third vision. India must stand up to the world. Because I believe that unless India 
               stands up to the world, no one will respect us. Only strength respects strength. We must be 
               strong not only as a military power but also as an economic power. Both must go hand-in-hand. 
               My good fortune was to have worked with three great minds. Dr. Vikram Sarabhai of the Dept. of 
               space, Professor Satish Dhawan, who succeeded him and Dr. Brahm Prakash, father of nuclear material.
               I was lucky to have worked with all three of them closely and consider this the great opportunity of my life. 
               I see four milestones in my career"""

In [19]:
# Text Cleaning
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer

In [21]:
# ps = PorterStemmer()  not using this because here Lemmatization is better than stemming
nltk.download('punkt')
wordnet=WordNetLemmatizer()
sentences = nltk.sent_tokenize(paragraph)


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


In [25]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.


True

In [26]:
sentences_modify = []

for i in range(len(sentences)):
    sen = re.sub('[^a-zA-Z]', ' ', sentences[i])  # Replace punctuation with space.
    sen = sen.lower()   # Lowercase
    sen_words = sen.split()   # Tokenization
    sen_final_words = [wordnet.lemmatize(word) for word in sen_words if not word in set(stopwords.words('english'))]   # Skip or Remove Stop words and lemmatize

    final_sen = ' '.join(sen_final_words)
    
    sentences_modify.append(final_sen)


# Every cell contains a number, that represents the count of the word in that particular text.
# All words have been converted to lowercase.
# The words in columns have been arranged alphabetically

In [27]:
 sentences_modify

['three vision india',
 'year history people world come invaded u captured land conquered mind',
 'alexander onwards greek turk mogul portuguese british french dutch came looted u took',
 'yet done nation',
 'conquered anyone',
 'grabbed land culture history tried enforce way life',
 '',
 'respect freedom others first vision freedom',
 'believe india got first vision started war independence',
 'freedom must protect nurture build',
 'free one respect u',
 'second vision india development',
 'fifty year developing nation',
 'time see developed nation',
 'among top nation world term gdp',
 'percent growth rate area',
 'poverty level falling',
 'achievement globally recognised today',
 'yet lack self confidence see developed nation self reliant self assured',
 'incorrect',
 'third vision',
 'india must stand world',
 'believe unless india stand world one respect u',
 'strength respect strength',
 'must strong military power also economic power',
 'must go hand hand',
 'good fortune worked

In [ ]:
for i in range(len(sentences)):
    print(sentences[i])

In [31]:
# Now this is the time to Creating the Bag of Words model 

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
X = cv.fit_transform(sentences_modify)

In [32]:
X

<31x114 sparse matrix of type '<class 'numpy.int64'>'
	with 155 stored elements in Compressed Sparse Row format>

In [33]:
X.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 1, 0],
       [0, 1, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [34]:
cv.get_feature_names()

['achievement',
 'alexander',
 'also',
 'among',
 'anyone',
 'area',
 'assured',
 'believe',
 'brahm',
 'british',
 'build',
 'came',
 'captured',
 'career',
 'closely',
 'come',
 'confidence',
 'conquered',
 'consider',
 'culture',
 'dept',
 'developed',
 'developing',
 'development',
 'dhawan',
 'done',
 'dr',
 'dutch',
 'economic',
 'enforce',
 'falling',
 'father',
 'fifty',
 'first',
 'fortune',
 'four',
 'free',
 'freedom',
 'french',
 'gdp',
 'globally',
 'go',
 'good',
 'got',
 'grabbed',
 'great',
 'greek',
 'growth',
 'hand',
 'history',
 'incorrect',
 'independence',
 'india',
 'invaded',
 'lack',
 'land',
 'level',
 'life',
 'looted',
 'lucky',
 'material',
 'milestone',
 'military',
 'mind',
 'mogul',
 'must',
 'nation',
 'nuclear',
 'nurture',
 'one',
 'onwards',
 'opportunity',
 'others',
 'people',
 'percent',
 'portuguese',
 'poverty',
 'power',
 'prakash',
 'professor',
 'protect',
 'rate',
 'recognised',
 'reliant',
 'respect',
 'sarabhai',
 'satish',
 'second',
 'se

In [36]:
cv.vocabulary_

{'achievement': 0,
 'alexander': 1,
 'also': 2,
 'among': 3,
 'anyone': 4,
 'area': 5,
 'assured': 6,
 'believe': 7,
 'brahm': 8,
 'british': 9,
 'build': 10,
 'came': 11,
 'captured': 12,
 'career': 13,
 'closely': 14,
 'come': 15,
 'confidence': 16,
 'conquered': 17,
 'consider': 18,
 'culture': 19,
 'dept': 20,
 'developed': 21,
 'developing': 22,
 'development': 23,
 'dhawan': 24,
 'done': 25,
 'dr': 26,
 'dutch': 27,
 'economic': 28,
 'enforce': 29,
 'falling': 30,
 'father': 31,
 'fifty': 32,
 'first': 33,
 'fortune': 34,
 'four': 35,
 'free': 36,
 'freedom': 37,
 'french': 38,
 'gdp': 39,
 'globally': 40,
 'go': 41,
 'good': 42,
 'got': 43,
 'grabbed': 44,
 'great': 45,
 'greek': 46,
 'growth': 47,
 'hand': 48,
 'history': 49,
 'incorrect': 50,
 'independence': 51,
 'india': 52,
 'invaded': 53,
 'lack': 54,
 'land': 55,
 'level': 56,
 'life': 57,
 'looted': 58,
 'lucky': 59,
 'material': 60,
 'milestone': 61,
 'military': 62,
 'mind': 63,
 'mogul': 64,
 'must': 65,
 'nation': 66

In [39]:

# encode document
vector = cv.transform(sentences_modify)
#summarize encoded vector
print(vector.shape)
print(vector.toarray())

(31, 114)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 1 1 0]
 [0 1 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [41]:
%load_ext google.colab.data_table
df = pd.DataFrame(vector.toarray(), columns=cv.get_feature_names())
df

The google.colab.data_table extension is already loaded. To reload it, use:
  %reload_ext google.colab.data_table


achievement  alexander  also  among  anyone  ...  way  worked  world  year  yet
0             0          0     0      0       0  ...    0       0      0     0    0
1             0          0     0      0       0  ...    0       0      1     1    0
2             0          1     0      0       0  ...    0       0      0     0    0
3             0          0     0      0       0  ...    0       0      0     0    1
4             0          0     0      0       1  ...    0       0      0     0    0
5             0          0     0      0       0  ...    1       0      0     0    0
6             0          0     0      0       0  ...    0       0      0     0    0
7             0          0     0      0       0  ...    0       0      0     0    0
8             0          0     0      0       0  ...    0       0      0     0    0
9             0          0     0      0       0  ...    0       0      0     0    0
10            0          0     0      0       0  ...    0       0      0     0    0
11            0          0     0      0       0  ...    0       0      0     0    0
12            0          0     0      0       0  ...    0       0      0     1    0
13            0          0     0      0       0  ...    0       0      0     0    0
14            0          0     0      1       0  ...    0       0      1     0    0
15            0          0     0      0       0  ...    0       0      0     0    0
16            0          0     0      0       0  ...    0       0      0     0    0
17            1          0     0      0       0  ...    0       0      0     0    0
18            0          0     0      0       0  ...    0       0      0     0    1
19            0          0     0      0       0  ...    0       0      0     0    0
20            0          0     0      0       0  ...    0       0      0     0    0
21            0          0     0      0       0  ...    0       0      1     0    0
22            0          0     0      0       0  ...    0       0      1     0    0
23            0          0     0      0       0  ...    0       0      0     0    0
24            0          0     1      0       0  ...    0       0      0     0    0
25            0          0     0      0       0  ...    0       0      0     0    0
26            0          0     0      0       0  ...    0       1      0     0    0
27            0          0     0      0       0  ...    0       0      0     0    0
28            0          0     0      0       0  ...    0       0      0     0    0
29            0          0     0      0       0  ...    0       1      0     0    0
30            0          0     0      0       0  ...    0       0      0     0    0

[31 rows x 114 columns]

### CountVectorizer Simply Understand
Convert a collection of text documents to a matrix of token counts
- [sklearn.feature_extraction.text.CountVectorizer](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html)


In [11]:
from sklearn.feature_extraction.text import CountVectorizer

In [12]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [13]:
dataset =["Eka thakar  cheye govir prem hote pare na na na",
        "nijer sathe kotha bolar cheye govir prem alap hote pare na",
        "This process is called feature extraction or vectorization" ] 

- [Using CountVectorizer to Extracting Features from Text | Geeksforgeeeks](https://www.geeksforgeeks.org/using-countvectorizer-to-extracting-features-from-text/)
- Every cell contains a number, that represents the count of the word in that particular text.
- All words have been converted to lowercase.
- The words in columns have been arranged alphabetically.

In [14]:

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(dataset)
vectorizer.get_feature_names()


# encode document
#vector = vectorizer.transform(text)
# summarize encoded vector
#print(vector.shape)
#print(vector.toarray())

['alap',
 'bolar',
 'called',
 'cheye',
 'eka',
 'extraction',
 'feature',
 'govir',
 'hote',
 'is',
 'kotha',
 'na',
 'nijer',
 'or',
 'pare',
 'prem',
 'process',
 'sathe',
 'thakar',
 'this',
 'vectorization']

In [15]:
X.toarray()

array([[0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 3, 0, 0, 1, 1, 0, 0, 1, 0, 0],
       [1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1]])

In [16]:
vectorizer.vocabulary_

{'alap': 0,
 'bolar': 1,
 'called': 2,
 'cheye': 3,
 'eka': 4,
 'extraction': 5,
 'feature': 6,
 'govir': 7,
 'hote': 8,
 'is': 9,
 'kotha': 10,
 'na': 11,
 'nijer': 12,
 'or': 13,
 'pare': 14,
 'prem': 15,
 'process': 16,
 'sathe': 17,
 'thakar': 18,
 'this': 19,
 'vectorization': 20}

In [43]:
# encode document
vector = vectorizer.transform(dataset)
#summarize encoded vector
print(vector.shape)
print(vector.toarray())

(3, 21)
[[0 0 0 1 1 0 0 1 1 0 0 3 0 0 1 1 0 0 1 0 0]
 [1 1 0 1 0 0 0 1 1 0 1 1 1 0 1 1 0 1 0 0 0]
 [0 0 1 0 0 1 1 0 0 1 0 0 0 1 0 0 1 0 0 1 1]]


In [44]:
%load_ext google.colab.data_table
df = pd.DataFrame(vector.toarray(), columns=vectorizer.get_feature_names())
df

The google.colab.data_table extension is already loaded. To reload it, use:
  %reload_ext google.colab.data_table


alap  bolar  called  cheye  eka  ...  process  sathe  thakar  this  vectorization
0     0      0       0      1    1  ...        0      0       1     0              0
1     1      1       0      1    0  ...        0      1       0     0              0
2     0      0       1      0    0  ...        1      0       0     1              1

[3 rows x 21 columns]