<a href="https://colab.research.google.com/github/Mynuddin-dev/NLP/blob/main/Word_Embedding_using_tensorflowkeras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[How to Use Word Embedding Layers for Deep Learning with Keras | Easily Understand](https://machinelearningmastery.com/use-word-embedding-layers-deep-learning-keras/)

#### Key Understand
- Sparse Vector Representation
- Dense Vector Representation
- Vector Space 
- Cosine Similarity
- Embeding
- Parameters in One_hot
- 1.Vocab Size.
- 2.Dimension.
- 3.Each Sen Length.

In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sentences =['The boss krish Naik',
     'The boss of data Science',
     'the cup of tea',
     'I am a good boy',
     'I am a good developer',
     'Understand the meaning of words',
     'Your Contents are good',]

In [3]:
sentences

['The boss krish Naik',
 'The boss of data Science',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'Understand the meaning of words',
 'Your Contents are good']

In [4]:
voc_size=10000

In [6]:
# One Hot Representation

onehot_repr=[one_hot(words,voc_size)for words in sentences] 
print(onehot_repr)

[[3018, 4427, 7013, 1119], [3018, 4427, 2249, 669, 4589], [3018, 2240, 2249, 3841], [5581, 6898, 9940, 4257, 9375], [5581, 6898, 9940, 4257, 8727], [8780, 3018, 441, 2249, 362], [2902, 6389, 2006, 4257]]


### Word Embedding Represntation

In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)   # pre 0 in first , Post 0 in last
print(embedded_docs)

[[   0    0    0    0 3018 4427 7013 1119]
 [   0    0    0 3018 4427 2249  669 4589]
 [   0    0    0    0 3018 2240 2249 3841]
 [   0    0    0 5581 6898 9940 4257 9375]
 [   0    0    0 5581 6898 9940 4257 8727]
 [   0    0    0 8780 3018  441 2249  362]
 [   0    0    0    0 2902 6389 2006 4257]]


In [9]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))    #Dimnesion =10
model.compile('adam','mse')

In [10]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [11]:
print(model.predict(embedded_docs))

[[[ 3.87843885e-02  1.04402676e-02 -3.67086418e-02 -2.15686094e-02
   -9.31227207e-03 -1.09378472e-02 -2.15791706e-02  5.57374209e-04
   -4.44530956e-02  2.00706013e-02]
  [ 3.87843885e-02  1.04402676e-02 -3.67086418e-02 -2.15686094e-02
   -9.31227207e-03 -1.09378472e-02 -2.15791706e-02  5.57374209e-04
   -4.44530956e-02  2.00706013e-02]
  [ 3.87843885e-02  1.04402676e-02 -3.67086418e-02 -2.15686094e-02
   -9.31227207e-03 -1.09378472e-02 -2.15791706e-02  5.57374209e-04
   -4.44530956e-02  2.00706013e-02]
  [ 3.87843885e-02  1.04402676e-02 -3.67086418e-02 -2.15686094e-02
   -9.31227207e-03 -1.09378472e-02 -2.15791706e-02  5.57374209e-04
   -4.44530956e-02  2.00706013e-02]
  [ 2.32465155e-02 -1.14946254e-02  3.95341553e-02  6.89063221e-03
   -5.18172979e-03 -4.55807336e-02 -4.70049269e-02 -4.24916856e-02
    1.09481439e-02 -4.01360765e-02]
  [-1.96437370e-02  3.65028046e-02  4.95512411e-03  2.69099809e-02
   -2.09504608e-02 -4.79495041e-02 -6.62031025e-03  8.02988932e-03
    4.66049202e-

In [12]:

embedded_docs[0]

array([   0,    0,    0,    0, 3018, 4427, 7013, 1119], dtype=int32)

In [13]:
print(model.predict(embedded_docs)[0])

[[ 0.03878439  0.01044027 -0.03670864 -0.02156861 -0.00931227 -0.01093785
  -0.02157917  0.00055737 -0.0444531   0.0200706 ]
 [ 0.03878439  0.01044027 -0.03670864 -0.02156861 -0.00931227 -0.01093785
  -0.02157917  0.00055737 -0.0444531   0.0200706 ]
 [ 0.03878439  0.01044027 -0.03670864 -0.02156861 -0.00931227 -0.01093785
  -0.02157917  0.00055737 -0.0444531   0.0200706 ]
 [ 0.03878439  0.01044027 -0.03670864 -0.02156861 -0.00931227 -0.01093785
  -0.02157917  0.00055737 -0.0444531   0.0200706 ]
 [ 0.02324652 -0.01149463  0.03953416  0.00689063 -0.00518173 -0.04558073
  -0.04700493 -0.04249169  0.01094814 -0.04013608]
 [-0.01964374  0.0365028   0.00495512  0.02690998 -0.02095046 -0.0479495
  -0.00662031  0.00802989  0.04660492 -0.03055015]
 [-0.04450325 -0.030677    0.01612966 -0.00775149  0.02897083 -0.01752838
   0.04553015  0.0232146  -0.0376      0.01168816]
 [-0.03102863 -0.02817935  0.01851321 -0.03619959  0.04767245  0.04350537
   0.04039312  0.03279069 -0.01879901  0.0144661 ]]


In [14]:
from numpy import array
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.embeddings import Embedding
# define documents
docs = ['Well done!',
		'Good work',
		'Great effort',
		'nice work',
		'Excellent!',
		'Weak',
		'Poor effort!',
		'not good',
		'poor work',
		'Could have done better.']
        
# define class labels for classification
labels = array([1,1,1,1,1,0,0,0,0,0])

# integer encode the documents
vocab_size = 50
encoded_docs = [one_hot(d, vocab_size) for d in docs]
print(encoded_docs)

# pad documents to a max length of 4 words
max_length = 4
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(padded_docs)

# define the model
model = Sequential()
model.add(Embedding(vocab_size, 8, input_length=max_length))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

# compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# summarize the model
print(model.summary())

# Finally, we can fit and evaluate the classification model.
model.fit(padded_docs, labels, epochs=50, verbose=0)

# evaluate the model
loss, accuracy = model.evaluate(padded_docs, labels, verbose=0)
print('Accuracy: %f' % (accuracy*100))

[[21, 41], [22, 33], [31, 28], [7, 33], [32], [33], [6, 28], [4, 22], [6, 33], [33, 26, 41, 12]]
[[21 41  0  0]
 [22 33  0  0]
 [31 28  0  0]
 [ 7 33  0  0]
 [32  0  0  0]
 [33  0  0  0]
 [ 6 28  0  0]
 [ 4 22  0  0]
 [ 6 33  0  0]
 [33 26 41 12]]
Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 4, 8)              400       
_________________________________________________________________
flatten (Flatten)            (None, 32)                0         
_________________________________________________________________
dense (Dense)                (None, 1)                 33        
Total params: 433
Trainable params: 433
Non-trainable params: 0
_________________________________________________________________
None
Accuracy: 80.000001


- Pre-Trained GloVe Embedding.
- In My System its very slow. But You can try